version: "3.9"

services:
  # MongoDB
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  # MongoDB Express
  mongo_express:
    container_name: mongo_express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo_db

  nextcrm-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
